{% set name = "jupytab" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f9f56c71ca63b318a2a5e5d1cb0ce3084a5662f710d6b51863aa3313887c075

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas

test:
  imports:
    - jupytab

about:
  home: https://github.com/CFMTech/jupytab
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Connect Tableau to your jupyter notebooks

  description: |
    Jupytab allows you to explore in Tableau data which is generated dynamically
    by a Jupyter Notebook. You can thus create Tableau data sources in a very 
    flexible way using all the power of Python. This is achieved by having Tableau 
    access data through a web server created by Jupytab.
  doc_url: https://github.com/CFMTech/jupytab
  dev_url: https://github.com/CFMTech/jupytab

extra:
  recipe-maintainers:
    - js-dieu
